async function tryGemini(prompt: string, apiKey: string) {
  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key=${apiKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        generationConfig: { responseModalities: ["IMAGE", "TEXT"] },
      }),
    }
  );

  const data = await res.json();

  if (!res.ok) {
    const errMsg = data?.error?.message || `Gemini API error (${res.status})`;
    console.error("GEMINI ERROR:", res.status, errMsg);
    if (res.status === 429) return { error: "⚠️ Rate limited. Wait a moment and try again.", status: 429 };
    if (res.status === 403 || res.status === 401) return { error: "❌ Invalid Gemini API key.", status: 401 };
    return { error: `⚠️ ${errMsg}`, status: 500 };
  }

  const parts = data?.candidates?.[0]?.content?.parts || [];
  const imagePart = parts.find((p: unknown) => (p as { inlineData?: { data?: string } })?.inlineData?.data);

  if (imagePart?.inlineData?.data) return { image: imagePart.inlineData.data };

  const textPart = parts.find((p: unknown) => (p as { text?: string })?.text);
  if (textPart) {
    return { error: "⚠️ Gemini returned text instead of an image. Try a more visual prompt.", content: (textPart as { text: string }).text, status: 500 };
  }

  return { error: "⚠️ No image generated. Try a different prompt.", status: 500 };
}

async function tryStability(prompt: string, apiKey: string) {
  const res = await fetch(
    "https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image",
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify({
        text_prompts: [{ text: prompt, weight: 1 }],
        cfg_scale: 7,
        height: 1024,
        width: 1024,
        steps: 30,
        samples: 1,
      }),
    }
  );

  const data = await res.json();

  if (!res.ok) {
    const errMsg = data?.message || `Stability API error (${res.status})`;
    console.error("STABILITY ERROR:", res.status, errMsg);
    if (res.status === 402) return { error: "⚠️ No Stability AI credits remaining.", status: 402 };
    if (res.status === 401) return { error: "❌ Invalid Stability AI API key.", status: 401 };
    return { error: `⚠️ ${errMsg}`, status: 500 };
  }

  const imageData = data?.artifacts?.[0]?.base64;
  if (imageData) return { image: imageData };

  return { error: "⚠️ No image generated by Stability AI.", status: 500 };
}

export async function POST(req: Request) {
  const { prompt } = await req.json();

  if (!prompt) {
    return Response.json({ error: "Prompt is required" }, { status: 400 });
  }

  const geminiKey = process.env.GEMINI_API_KEY;
  const stabilityKey = process.env.STABILITY_API_KEY;

  if (geminiKey) {
    const result = await tryGemini(prompt, geminiKey);
    if (result.image) return Response.json({ content: null, image: result.image });
    if (result.status !== 429 && result.status !== 500) {
      return Response.json({ error: result.error, content: result.content }, { status: result.status || 500 });
    }
    console.log("Gemini failed, falling back to Stability AI");
  }

  if (stabilityKey) {
    const result = await tryStability(prompt, stabilityKey);
    if (result.image) return Response.json({ content: null, image: result.image });
    return Response.json({ error: result.error }, { status: result.status || 500 });
  }

  return Response.json(
    { error: "❌ No image API configured. Add GEMINI_API_KEY or STABILITY_API_KEY to .env.local" },
    { status: 500 }
  );
}
